//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DasContract.Blockchain.Plutus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DasContract.Blockchain.Plutus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module {{ p.Name }} where
        ///
        ///{% for library in p.Libraries %}
        ///import {{library}}
        ///{% endfor %}
        ///--
        ///--
        ///{% for function in p.WalletFunctions %}
        ///{{ function.GeneratedFunction }}
        ///
        ///{% endfor %}
        ///
        ///{% if p.WalletFunctions.size != 0 %}
        ///$(mkFunctions[&apos;{% assign functionNames = p.WalletFunctions | map: &apos;Name&apos; %}{{ functionNames | join: &quot;, &apos;&quot; }}])
        ///{% endif %}.
        /// </summary>
        public static string FluidSmartContractStructure {
            get {
                return ResourceManager.GetString("FluidSmartContractStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ p.Name }} :: MonadWallet m =&gt; m()
        ///{{ p.Name }} = logMsg &quot;{{ p.Message }}&quot;.
        /// </summary>
        public static string LogAMessage {
            get {
                return ResourceManager.GetString("LogAMessage", resourceCulture);
            }
        }
    }
}
