#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

# docker build -f "S:\_Školní projekty\BI-BAP\Bakaláøská práce\DasContract.Editor\DasContract.Editor.Server\Dockerfile" --force-rm -t dascontracteditorserver  --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=DasContract.Editor.Server" "S:\_Školní projekty\BI-BAP\Bakaláøská práce\DasContract.Editor"

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["DasContract.Editor.Server/DasContract.Editor.Server.csproj", "DasContract.Editor.Server/"]
COPY ["DasContract.DataPersistence.Repositories/DasContract.Editor.DataPersistence.Repositories.csproj", "DasContract.DataPersistence.Repositories/"]
COPY ["DasContract.DataPersistence.DbContexts/DasContract.Editor.DataPersistence.DbContexts.csproj", "DasContract.DataPersistence.DbContexts/"]
COPY ["DasContract.Editor.DataPersistence.ContractFileSession/DasContract.Editor.DataPersistence.Entities.csproj", "DasContract.Editor.DataPersistence.ContractFileSession/"]
COPY ["DasContract.Editor.Entities.Serialization.XML/DasContract.Editor.Entities.Serialization.XML.csproj", "DasContract.Editor.Entities.Serialization.XML/"]
COPY ["DasContract.Editor.Entities/DasContract.Editor.Entities.csproj", "DasContract.Editor.Entities/"]
COPY ["DasContract.Editor.Migrator/DasContract.Editor.Migrator.csproj", "DasContract.Editor.Migrator/"]
COPY ["DasContract.Editor.Migrator.Interface/DasContract.Editor.Migrator.Interfaces.csproj", "DasContract.Editor.Migrator.Interface/"]
COPY ["Bonsai.Utils.Property/Bonsai.Utils.Property.csproj", "Bonsai.Utils.Property/"]
COPY ["DasContract.Editor.Migrator.Extensions/DasContract.Editor.Migrator.Extensions.csproj", "DasContract.Editor.Migrator.Extensions/"]
COPY ["DasContract.Editor.Interfaces/DasContract.Editor.Interfaces.csproj", "DasContract.Editor.Interfaces/"]
COPY ["DasContract.DataPersistence.Repositories.Interfaces/DasContract.Editor.DataPersistence.Repositories.Interfaces.csproj", "DasContract.DataPersistence.Repositories.Interfaces/"]
COPY ["DasContract.Editor.Pages.Main/DasContract.Editor.Pages.Main.csproj", "DasContract.Editor.Pages.Main/"]
COPY ["Bonsai.Utils.String/Bonsai.Utils.String.csproj", "Bonsai.Utils.String/"]
COPY ["Bonsai.RazorComponents.Interfaces/Bonsai.RazorComponents.Interfaces.csproj", "Bonsai.RazorComponents.Interfaces/"]
COPY ["DasContract.Editor.Components.Main/DasContract.Editor.Components.Main.csproj", "DasContract.Editor.Components.Main/"]
COPY ["DasContract.Editor.Entities.Integrity/DasContract.Editor.Entities.Integrity.csproj", "DasContract.Editor.Entities.Integrity/"]
COPY ["Bonsai.RazorComponents.MaterialBootstrap/Bonsai.RazorComponents.MaterialBootstrap.csproj", "Bonsai.RazorComponents.MaterialBootstrap/"]
COPY ["Bonsai.Services.LanguageDictionary/Bonsai.Services.LanguageDictionary.csproj", "Bonsai.Services.LanguageDictionary/"]
COPY ["Bonsai.Services.Interfaces/Bonsai.Services.Interfaces.csproj", "Bonsai.Services.Interfaces/"]
COPY ["DasContract.Editor.Utils.String/DasContract.Editor.Utils.String.csproj", "DasContract.Editor.Utils.String/"]
COPY ["DasContract.Editor.AppLogic.Facades.Interfaces/DasContract.Editor.AppLogic.Facades.Interfaces.csproj", "DasContract.Editor.AppLogic.Facades.Interfaces/"]
COPY ["Bonsai.Tests.Utils.String/Bonsai.Tests.Utils.String.csproj", "Bonsai.Tests.Utils.String/"]
COPY ["Bonsai.RazorPages.Error/Bonsai.RazorPages.Error.csproj", "Bonsai.RazorPages.Error/"]
COPY ["DasContract.Editor.AppLogic.Facades/DasContract.Editor.AppLogic.Facades.csproj", "DasContract.Editor.AppLogic.Facades/"]
RUN dotnet restore "DasContract.Editor.Server/DasContract.Editor.Server.csproj"
COPY . .
WORKDIR "/src/DasContract.Editor.Server"
RUN dotnet build "DasContract.Editor.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DasContract.Editor.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=publish /app .
RUN mv -n wwwroot/* DasContract.Editor.Pages.Main/dist
RUN rm -rf wwwroot/
ENTRYPOINT ["dotnet", "DasContract.Editor.Server.dll"]

FROM nginx:alpine
WORKDIR /var/www/web
COPY --from=publish /app/publish .
COPY DasContract.Editor.Server/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80